### ISSUE TITLE
Feature Request: Weather Blueprint

### ISSUE THREAD

**Issue by SKis274** [smarthomejunkie/Ulanzi-Awtrix-BluePrints#6]
Hi there!
Thank you for hard work in these easy to use blueprints for the ulanzi desktop clock.
Today I used the weather blueprint and imported the icons - it's so simple.

I'm located in germany and the weather state is displayed as "sunny" instead of "sonnig". Is there a way to implement other languages?
Or for the start another toggle switch in the blueprint like "Show Wind Speed" to hide the entire state text as "Show Weather Text"?

I hope this is possible and easy to add one of these feature :-)

**Comment by smarthomejunkie** [comment]
You can create a custom template that translates the weather conditions into your own language, but it might be a challenge to use that template as a sensor for the weather blueprint. You might be able to use the sensor app blueprint to show weather conditions in your own language using a custom template.

I will think about this more to see if I can find a solution for this in the blueprint.

**Comment by RedQuarck** [comment]
Just a testimony here: I do not use the dedicated weather blueprint since @smarthomejunkie added a Template (Optionnal) field in the **Sensor App** Blueprint:

In this way, you can design your own Weather App using any weather sensor:

This Template :
`{{ states('sensor.openweathermap_weather') | upper }} {{ state_attr('weather.openweathermap', 'temperature') | int }} °C {{ state_attr('weather.openweathermap', 'wind_speed') | int }} km/h`
will print the weather in your own language you selected it in the openweather integration configuration.

And for the icon:
`{{ states('weather.openweathermap') }}`

This is an example with Openweathermap, but it will work with any weather provider delivering a specific translated sensor for weather condition.
